port: 3333
targets:
  api1:
    methods: [GET, POST]
    delay: 100 # in milliseconds
    response:
      {
        "test": 123
      }

  api2:
    methods: [GET]
      # TODO: Add ranges for delay.
      # For now, delay only takes a fixed number of milliseconds to sleep
      # delay: "1000ms..5000ms"
    delay: 5000
    response:
      {
        "foo": 42,
        "bar": "elephant",
        "baz": [1, 2, 4, 8, 16, 32],
      }
  bad_api:
    methods: [TEST]
